# Generated by Django 4.2.7 on 2025-11-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investigationmember",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
