# Generated by Django 4.2.7 on 2025-11-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0002_investigationmember_last_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="entity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("person", "Personne"),
                    ("location", "Lieu"),
                    ("evidence", "Preuve"),
                    ("event", "Événement"),
                ],
                max_length=10,
            ),
        ),
    ]
