# Generated by Django 4.2.7 on 2025-11-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0003_entity_address_alter_entity_entity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="event_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entity",
            name="is_timeslot",
            field=models.BooleanField(default=False),
        ),
    ]
