# Generated by Django 4.2.7 on 2025-11-09 23:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0004_entity_event_end_date_entity_is_timeslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(blank=True, max_length=7)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "investigation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="investigation.investigation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("investigation", "name")},
            },
        ),
        migrations.AddField(
            model_name="entity",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="entities", to="investigation.tag"
            ),
        ),
    ]
