# Generated by Django 4.2.7 on 2025-11-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0005_tag_entity_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="entity",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="entity_photos/"),
        ),
    ]
